import 'package:e_book_app/Models/book_model.dart';

var categoryData=[
  {
    "icon":"Assets/Icons/heart.svg",
    "lebel":"Romance",
  },
  {
    "icon":"Assets/Icons/world.svg",
    "lebel":"Documentary",
  },{
    "icon":"Assets/Icons/plane.svg",
    "lebel":"Travel",
  },
  {
    "icon":"Assets/Icons/heart.svg",
    "lebel":"Love story",
  },
];

var bookData=[
  BookModel(
    id: "1",
    title: "Boundraties mmmmm ygyuivfgftcrtt f6ftyytf",
    description: "hhhh bnnnnnnnnngngggggggggggggggggggggggggfgffffffffffffffffffffffffffff",
    aboutAuthor: "hi my name is mallas and i written this book",
    audioLen: "20",
    author: "Mallas",
    coverUrl: "Assets/Images/boundraries.jpg",
    rating: "4.2",
    category: "Documentary",
     price: 100,
    numberofRating: "99999",
    pages: 23,
    language: "Urdu",
     bookurl: 'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
  ),
  BookModel(
    id: "2",
    title: "Daily Stoice",
    description: "hhhh bnnnnnnnnngngggggggggggggggggggggggggfgffffffffffffffffffffffffffff",
    aboutAuthor: "hi my name is mallas and i written this book",
    audioLen: "20",
    author: "Mallas",
    coverUrl: "Assets/Images/daily stoic.jpg",
    rating: "4.2",
    category: "Documentary",
     price: 100,
    numberofRating: "99999",
    pages: 3,
    language: "En",
    bookurl: 'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
  ),
  BookModel(
    id: "3",
    title: "Give and take",
    description: "hhhh bnnnnnnnnngngggggggggggggggggggggggggfgffffffffffffffffffffffffffff",
    aboutAuthor: "hi my name is mallas and i written this book",
    audioLen: "20",
    author: "Mallas",
    coverUrl: "Assets/Images/Give and Take.jpg",
    rating: "4.2",
    category: "Documentary",
    numberofRating: "99999",
     price: 100,
    pages: 23,
    language: "France",
    bookurl: 'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
  ),
  BookModel(
    id: "4",
    title: "When the moon split",
    description: "hhhh bnnnnnnnnngngggggggggggggggggggggggggfgffffffffffffffffffffffffffff",
    aboutAuthor: "hi my name is mallas and i written this book",
    audioLen: "20",
    author: "Mallas",
    coverUrl: "Assets/Images/When the moon split.jpg",
    rating: "4.2",
    category: "Documentary",
    numberofRating: "99999",
     price: 100,
    pages: 23,
    language: "En",
    bookurl: 'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
  ),
];